Repository honeycombio/agentless-integrations-for-aws, pull requests merged in 2021-11, with the labels that each got.

#81 docs: update key encryption
  README.md
Labels: version: no bump, type: documentation

#80 Debug mode
  common/common.go
Labels: type: enhancement, version: bump minor

#86 Prep Release v2.3.0
  CHANGELOG.md
Labels: status: blocked

#82 docs: add a note about debugging
  README.md
Labels: version: no bump, type: documentation
