Repository honeycombio/agentless-integrations-for-aws, pull requests merged in 2022-11, with the labels that each got.

#150 Embed service regexs into code
  common/common.go
  sam-templates/vpc-flow-logs.yml
  templates/aws-alb-logs.yml
  templates/aws-elb-logs.yml
  templates/s3-bucket-logs.yml
  templates/vpc-flow-logs.yml
  terraform/vpc-flow-logs.tf
Labels: type: enhancement, version: bump minor

#161 publish every main build to S3
  .circleci/config.yml
  publish_aws.sh
Labels: version: no bump, type: maintenance

#160 RDS Lambda transforms
  build.sh
  rds-mysql-kfh-transform/main.go
  rds-postgresql-kfh-transform/main.go
Labels: type: enhancement, version: bump minor, status: oncall

#170 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#172 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump

#173 maint: transfer to api team
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/add-to-project-v2.yml
Labels: no-changelog
