Repository honeycombio/agentless-integrations-for-aws, pull requests merged in 2022-10, with the labels that each got.

#140 Fixed a typo
  terraform/cloudwatch-logs-json.tf
Labels: version: no bump, type: documentation

#144 [release] v2.4.4
  CHANGELOG.md
Labels: version: no bump, type: maintenance

#145 [s3] fix bug in sampling & exception cases
  s3-handler/main.go
Labels: type: bug, version: bump patch

#146 [release] v2.4.5
  CHANGELOG.md
Labels: version: no bump, type: maintenance

#149 maint: add release file
  .github/release.yml
Labels: version: no bump, type: maintenance, merge at will, no-changelog

#148 [s3] Protect against Intn panicing if sample rate is set to 0
  common/common.go
Labels: type: bug, merge at will, status: oncall

#152 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
  .github/workflows/re-triage.yml
Labels: version: no bump, type: maintenance, merge at will
